main:
  push:
    - stages:
        - name: sync
          imports: https://cnb.cool/PPKunOfficial/berry-api-secrets/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/PPKunOfficial/berry-api.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
