# 测试新功能的简化配置文件
[settings]
health_check_interval_seconds = 30
request_timeout_seconds = 30
max_retries = 3
circuit_breaker_failure_threshold = 5
circuit_breaker_timeout_seconds = 60
recovery_check_interval_seconds = 120
max_internal_retries = 2
health_check_timeout_seconds = 10

[settings.smart_ai]
enabled = true
confidence_threshold = 0.3
health_check_interval_seconds = 60
connectivity_check_timeout_seconds = 5

# Provider配置 - 测试自定义HTTP头功能
[providers.openai_test]
name = "OpenAI Test Provider"
base_url = "https://httpbin.org"
api_key = "test-openai-key"
models = ["gpt-4", "gpt-3.5-turbo"]
enabled = true
timeout_seconds = 30
max_retries = 3
backend_type = "openai"
headers = { "X-Custom-Client" = "berry-api", "X-Version" = "1.0" }

[providers.azure_test]
name = "Azure Test Provider"
base_url = "https://httpbin.org"
api_key = "test-azure-key"
models = ["gpt-4", "gpt-35-turbo"]
enabled = true
timeout_seconds = 30
max_retries = 3
backend_type = "openai"
headers = { "X-Azure-Client" = "berry-api" }

# 模型配置
[models.gpt-4]
name = "GPT-4"
enabled = true
strategy = "weighted_failover"

[[models.gpt-4.backends]]
provider = "openai_test"
model = "gpt-4"
weight = 0.6
priority = 1
enabled = true
tags = ["premium", "fast"]
billing_mode = "per_token"

[[models.gpt-4.backends]]
provider = "azure_test"
model = "gpt-4"
weight = 0.4
priority = 2
enabled = true
tags = ["premium", "stable"]
billing_mode = "per_token"

[models.gpt-3.5-turbo]
name = "GPT-3.5 Turbo"
enabled = true
strategy = "smart_weighted_failover"

[[models.gpt-3.5-turbo.backends]]
provider = "openai_test"
model = "gpt-3.5-turbo"
weight = 0.7
priority = 1
enabled = true
tags = ["basic", "fast"]
billing_mode = "per_request"

# 用户配置 - 测试标签和速率限制功能
[users.admin_user]
name = "Admin User"
token = "admin-token-123"
enabled = true
allowed_models = []
tags = ["premium", "admin"]
rate_limit = { requests_per_minute = 1000, requests_per_hour = 10000, requests_per_day = 100000 }

[users.premium_user]
name = "Premium User"
token = "premium-token-456"
enabled = true
allowed_models = ["gpt-4"]
tags = ["premium"]
rate_limit = { requests_per_minute = 100, requests_per_hour = 1000, requests_per_day = 10000 }

[users.basic_user]
name = "Basic User"
token = "basic-token-789"
enabled = true
allowed_models = ["gpt-3.5-turbo"]
tags = ["basic"]
rate_limit = { requests_per_minute = 10, requests_per_hour = 100, requests_per_day = 1000 }

[users.limited_user]
name = "Limited User"
token = "limited-token-def"
enabled = true
allowed_models = ["gpt-3.5-turbo"]
tags = []
rate_limit = { requests_per_minute = 2, requests_per_hour = 20, requests_per_day = 200 }
